package com.jheng.app.admin.entity;

// Generated 2015-7-5 21:21:51 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import com.jheng.app.foundation.entity.BaseEntity;

/**
 * Manageadmin generated by hbm2java
 */
@Entity
@Table(name = "ManageAdmin", catalog = "mylevel")
public class Manageadmin extends BaseEntity implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = -9097728661623513046L;
	private String adminName;
	private String adminPwd;
	private String lastLogIp;
	private String privilege;

	public Manageadmin()
	{
	}

	public Manageadmin(String adminName, String adminPwd, String lastLogIp,
			String privilege)
	{
		this.adminName = adminName;
		this.adminPwd = adminPwd;
		this.lastLogIp = lastLogIp;
		this.privilege = privilege;
	}

	@Column(name = "adminName", length = 50)
	public String getAdminName()
	{
		return this.adminName;
	}

	public void setAdminName(String adminName)
	{
		this.adminName = adminName;
	}

	@Column(name = "adminPwd", length = 50)
	public String getAdminPwd()
	{
		return this.adminPwd;
	}

	public void setAdminPwd(String adminPwd)
	{
		this.adminPwd = adminPwd;
	}

	@Column(name = "lastLogIP", length = 50)
	public String getLastLogIp()
	{
		return this.lastLogIp;
	}

	public void setLastLogIp(String lastLogIp)
	{
		this.lastLogIp = lastLogIp;
	}

	@Column(name = "privilege")
	public String getPrivilege()
	{
		return this.privilege;
	}

	public void setPrivilege(String privilege)
	{
		this.privilege = privilege;
	}

}
