package com.jheng.app.web.entity;
// Generated 2015-7-27 23:04:23 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import com.jheng.app.foundation.entity.BaseEntity;

/**
 * Chargerecord generated by hbm2java
 */
@Entity
@Table(name = "chargerecord", catalog = "mylevel")
public class Chargerecord extends BaseEntity implements java.io.Serializable {

	private static final long serialVersionUID = -7981053964061716879L;

	private Member member;

	private BigDecimal chargeBalance;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "memberId")
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@Column(name = "chargeBalance", precision = 11)
	public BigDecimal getChargeBalance() {
		return this.chargeBalance;
	}

	public void setChargeBalance(BigDecimal chargeBalance) {
		this.chargeBalance = chargeBalance;
	}

}
