package com.jheng.app.web.entity;
// Generated 2015-7-27 23:04:23 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import com.jheng.app.foundation.entity.BaseEntity;

/**
 * Member generated by hbm2java
 */
@Entity
@Table(name = "member", catalog = "mylevel")
public class Member extends BaseEntity implements java.io.Serializable {

	private static final long serialVersionUID = 8347251075361964729L;
	private String membername;
	private String email;
	private String pwd;
	private String gender;
	private BigDecimal balance;
	private Double discount;
	private Integer score;
	private Integer clientType;
	private Set<Sheet> sheetsForTrainerId = new HashSet<Sheet>(0);
	private Set<Chargerecord> chargerecords = new HashSet<Chargerecord>(0);
	private Set<Sheet> sheetsForMemberId = new HashSet<Sheet>(0);

	@Column(name = "membername", length = 50)
	public String getMembername() {
		return this.membername;
	}

	public void setMembername(String membername) {
		this.membername = membername;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "pwd", length = 50)
	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	@Column(name = "gender", length = 4)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "balance", precision = 11)
	public BigDecimal getBalance() {
		return this.balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	@Column(name = "discount", precision = 2)
	public Double getDiscount() {
		return this.discount;
	}

	public void setDiscount(Double discount) {
		this.discount = discount;
	}

	@Column(name = "score")
	public Integer getScore() {
		return this.score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

	@Column(name = "clientType")
	public Integer getClientType() {
		return this.clientType;
	}

	public void setClientType(Integer clientType) {
		this.clientType = clientType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "memberByTrainerId")
	public Set<Sheet> getSheetsForTrainerId() {
		return this.sheetsForTrainerId;
	}

	public void setSheetsForTrainerId(Set<Sheet> sheetsForTrainerId) {
		this.sheetsForTrainerId = sheetsForTrainerId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<Chargerecord> getChargerecords() {
		return this.chargerecords;
	}

	public void setChargerecords(Set<Chargerecord> chargerecords) {
		this.chargerecords = chargerecords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "memberByMemberId")
	public Set<Sheet> getSheetsForMemberId() {
		return this.sheetsForMemberId;
	}

	public void setSheetsForMemberId(Set<Sheet> sheetsForMemberId) {
		this.sheetsForMemberId = sheetsForMemberId;
	}

}
